### ISSUE TITLE
Test Bug Color

### ISSUE THREAD

**Issue by EdossProject** [eu-digital-green-certificates/dgca-verifier-app-android#194]
Wen i try toGreetings,
I tried to scan a test and it comes out green, even though it has expired. Shouldn't it come out red with EXPIRED?
![a3111685-f5c2-4c06-add7-09c8f60c9ac1](https://user-images.githubusercontent.com/88037505/131487216-81fb1b7f-c6fe-4fb8-9080-614622accd03.jpg)

**Comment by EdossProject** [comment]
UP!

**Comment by kerstin-oppermann-tsi** [comment]
@EdossProject can you check this issue again please?

**Comment by EdossProject** [comment]
Have you update?

**Comment by EdossProject** [comment]
If i use C19 app i riceve
![6d9fed3e-46b7-47ca-80b2-4866c340826e](https://user-images.githubusercontent.com/88037505/133767610-cf990a5c-ce1f-49b6-b2b1-2203a77f222c.jpg)

Whit your App:
![bf98d5fd-3fbb-4ef9-bec2-13a87e3d4f9c](https://user-images.githubusercontent.com/88037505/133767648-7988962f-b6fc-444c-9fc7-f2cf426a2513.jpg)

Can I fix ita?

**Comment by kerstin-oppermann-tsi** [comment]
can you send me your test code?

**Comment by EdossProject** [comment]
> can you send me your test code?

What would it be? What voice do I extract it from?

**Comment by kerstin-oppermann-tsi** [comment]
The QR Code from your test which you scanned for the result.

**Comment by EdossProject** [comment]
Find it below
![133767648-7988962f-b6fc-444c-9fc7-f2cf426a2513](https://user-images.githubusercontent.com/88037505/133773184-56bc6221-1cf4-4de5-8557-b3d7546b7258.jpg)
:

**Comment by EdossProject** [comment]
Find it below
![2aaeddbe-2310-4d5f-babe-db81187fdea0](https://user-images.githubusercontent.com/88037505/133773244-cb25d0e5-d091-4fd4-b201-0cd87872c1cc.jpg)
:

**Comment by Light2288** [comment]
@EdossProject @kerstin-oppermann-tsi  i think the reason is that VerificaC19 embeds some custom medical rules for validation, different from the european implementation (because when they were added, there were no european implementation for "medical" validation with business rules, only for "technical" validation)
So for VerificaC19 the DCC is not valid anymore (for italian medical rules, a test is valid for 48h), while for the eurpean app this is a perfectly fine DCC (i don't think that italian business rules with european format exist yet, but i can be wrong on this)
Hope this helps

**Comment by EdossProject** [comment]
In my opinion, a valid solution can be to verify that the test has been performed and check that 48 hours have not passed from the date of issue to that of reading.
