### ISSUE TITLE
No Download Certificate

### ISSUE THREAD

**Issue by EdossProject** [eu-digital-green-certificates/dgca-verifier-app-android#230]
Hi, it is from 27/09/21 that the certificates are no longer downloaded. What may have happened?

**Comment by EdossProject** [comment]
UP!

**Comment by oliversaggau** [comment]
The used servers https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/blob/main/app/src/acc/assets/verifier-context.jsonc#L22 and https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/blob/main/app/src/tst/assets/verifier-context.jsonc#L22 give 404

**Comment by EdossProject** [comment]
Do you have a solution to solve?

**Comment by oliversaggau** [comment]
Nope, unfortunately not. I used those servers myself and don't know what happened or if there are other servers/mirrors we could use.

**Comment by EdossProject** [comment]
C19 app work, can you use it?

**Comment by EdossProject** [comment]
If you wont, i have repo.

**Comment by EdossProject** [comment]
I have found this online: https://get.dgc.gov.it/v1/dgc/signercertificate/update

**Comment by daniel-eder** [comment]
Please see https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/218#issuecomment-925566524
The test environment is a service provided for the EU member states and countries in the official onboarding process. 
Due to the high amount of traffic it is only available during limited periods for testing in schedule with the EU onboarding processes.
