### ISSUE TITLE
Certificate or Pass? Assessment of the impact on society of the certificate.

### ISSUE THREAD

**Issue by loic86** [eu-digital-green-certificates/dgca-verifier-app-android#247]
Hi guys,
I have a question. 
Based on the [Regulation 2021/953](https://eur-lex.europa.eu/legal-content/EN/TXT/?toc=OJ%3AL%3A2021%3A211%3ATOC&uri=uriserv%3AOJ.L_.2021.211.01.0001.01.ENG) that institutes the "EU Digital Covid Certificate" basically states that the main 2 goals are:
1) Facilitate Free movement and Travel between states, so a control limited in the scenario of cross-border controls.
2) Interoperability between states.

granting the principles of proportionality and non discrimination.
Now, after six months of the institution (15/06 the regulation, 01/07 application), granted the fact that the member states are implementing this certificate not in the limited scenario that you engineers, architects and developers were imagining: a tool to facilitate border controls, but rather as a pass to impose vaccination through discrimination, now even introducing revocation and applying this control on every aspect of life, on some states even for the right to work and restricting the policies to remove the "proof of test" (Article 6 of 2021/953) aka "2G". How do you feel about that? 
I imagine and hope that the majority of you had not in mind this scenario, can't you do anything about it? Or you agree on this misuse of the certification transforming it into a pass, against the principles that Regulation 2021/953 itself invokes? Just some highlights:
- "proportionality and non-discrimination": p.3 (14); 
- "No 2G policies": p.7 (36);  
- "Fundamental Rights of the person": p.11 (62); 
- "revocation lists in limited cases", so no what the countries are implementing now. p.4 (19).

There will be a second report by 31/03/2022, I think that also you will have a voice on that, what will be your judgement? Respecting the principles of open source will be of vital importance to see here an open discussion on your evaluation on the political and societal effects of these certificates that you developed.

**Comment by daniel-eder** [comment]
While a discussion about impacts of this technology certainly is merited, I am sorry to say, this is not the right place for it. In this GitHub organization we focus on the implementation and technical challenges, not the political and ethical side of things.

As we do not have the capacity to moderate such discussions and keep them in line with our code of conduct I will close this issue, but I hope you can find a place to discuss the philosophical side of this project.

**Comment by loic86** [comment]
Hi Daniel,
Thank you for your answer.
I understand what you are saying, but IMHO I believe that a retrospective analysis is needed and would be of big value, if you really believe on the open source philosophy, to keep it open and transparent, especially in the case of this tool, is not a normal IT project, is a project with an unprecedented impact on society which is being greatly abused from the stated goals and I think that cannot be treated with the standard management policies: "technicians just implement tech, here is not the right place", as a developer I honestly find this answer also disrespectful for the developers of the team.
I strongly believe that when you and the team joined the project - especially for team members that believe on open source software principles - you did it for the positive impact that you were projecting and did not imagine such a drift.
In any case, can you please redirect me to a place that you find more suited to arise these concerns?
I hope that you and the team read at least once Hannah Arendt and you are aware of the responsibility and commitment that you have on this moment and I hope that though you still find here not a good place to discuss but you are at least discussing the evident discrepancies in the usage and pushing these instances internally.

**Comment by daniel-eder** [comment]
Hi oic86,

I'll respond here to both your update and the new ticket #248.
Naturally, people working on this project also hold their own views in regard to how it develops, however due to the target audience (developers, not politicians) such discussions do not take place here.

Due to our role in this project as contractors we are also not in a position to influence policy - we have no say in questions of this magnitude, and from a democratic perspective that is *good*, because we only represent our own views, not those of the larger population.
 
You asked about the proper place to raise these concerns - in the end this comes down to a democratic process. To effect a discussion or change in policy any EU citizen primarily needs to talk to their political representatives or get their attention via (social) media. 

The European Commission additionally offers a feedback platform: https://ec.europa.eu/info/law/better-regulation/have-your-say_en, which has an initiative regarding covid vaccination: https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13016-Coronavirus-health-certificate-scheme-technical-specifications-&-rules-for-Digital-Green-Certificate_en
